### ISSUE TITLE
Allow running with no sandbox mode

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dnitsch/uistrategy#4]
To get around these errors:
```
[0203/131655.224009:ERROR:zygote_host_impl_linux.cc(100)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

Something like:
```yml
  browserConfig:
    headless: true
    noSandbox: true
```

and passing `--no-sandbox` to the Chromium instance
