### ISSUE TITLE
Ability to capture Output from selectors in the report

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dnitsch/uistrategy#7]
It'd be nice to be able to get the values of the selectors inside the report for later parsing.

e.g.:
```yml
- name: "for"
  captureOutput: true
  element:
    selector: //h1/text()
```

And then see it in the report:
```json
"for": {
        "screenshot": "",
        "errored": false,
        "message": "found element: //h1/text()",
        "output": ["500"]
},
```

This would allow me to use this project instead of `dom-curl` and remove Node JS from this: https://github.com/ElvenSpellmaker/PaypalFundraiserSlackNotifier
